package com.dreamscloud.deneme.ai

/*
* HATALAR
* 3 HAMLE TEKRARI BERABERE OLMUYOR
* SESLİ HAMLEDE KALE E A3 YAPAMIYOR
* KALE E A3 DİYE SESLENDİREMİYOR
* BİLGİSAYARA DÜŞÜNME MOTORU EKLENECEK
* EKLENECEKLER
* ARALIKSIZ SEES İLE OYNAMA
* ÇERÇEVEYİ KALDIRMA DEFAULT TRUE
* TAŞ İCONU DEĞİŞTİREBİLME
* TAHTA RENGİ DEĞİŞTİREBİLME
* KAZANINCA ALKIŞ
* OYUN İÇİ SATIN ALMA
* İNSTANT APP
* HAMLELERİ YAZMA
* ONLİNE OYUN
* ARAMA EKLE
* ARKADAŞ EKLEME SEÇENEĞİ
* OTOMATİK EŞLEŞTİRME
* OFFLİNE OLUNCA SERVİS İLE BİLGİ ALMA
* SON ONLİNE SAATİNİ YAZMA
* OYUNDA İKEN RAKİP OYUNDAN ÇIKARSA UYARMA
* OYUN BİTİNCE BAŞKA OYUN HAZIRLAYABİLME
* HER AKTİVİTEDE OYUN TEKLİFİ ALABİLME
* RAKİBİN OLASI HAMLELERİNİ GÖREMEME
* GMAİL ADRESLERİ HASHLENEBİLİR
* ONLİNE OYUNDA OYUN BİTİNCE MAİN MENU VE YENİ OYUN ÇALIŞMIYOR
* ONLİNE OYUNA GİRERKEN MAİN MENUYU KAPATIYOR
 */